// pages/TermsOfService.js
import React from "react";
import { Link } from "react-router-dom";

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-blue-50 py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-4xl lg:text-5xl font-bold text-gray-900 mb-4">
            Terms of Service
          </h1>
          <p className="text-xl text-gray-600">
            Last updated: {new Date().toLocaleDateString()}
          </p>
        </div>

        {/* Breadcrumb */}
        <div className="flex items-center space-x-2 text-sm text-gray-500 mb-8">
          <Link to="/" className="hover:text-purple-600">
            Home
          </Link>
          <span>›</span>
          <span>Terms of Service</span>
        </div>

        {/* Content */}
        <div className="bg-white rounded-2xl shadow-lg p-8">
          <div className="prose prose-lg max-w-none">
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                1. Acceptance of Terms
              </h2>
              <p className="text-gray-700 mb-4">
                By accessing and using DesignHub ("the Service"), you accept and
                agree to be bound by the terms and provision of this agreement.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                2. Use License
              </h2>
              <p className="text-gray-700 mb-4">
                Permission is granted to temporarily use DesignHub's tools for
                personal and commercial projects. This is the grant of a
                license, not a transfer of title.
              </p>
              <p className="text-gray-700 mb-4">
                Under this license you may not:
              </p>
              <ul className="list-disc list-inside text-gray-700 space-y-2 mb-4">
                <li>Modify or copy the materials for redistribution</li>
                <li>
                  Use the materials for any commercial purpose beyond your own
                  projects
                </li>
                <li>Attempt to decompile or reverse engineer any software</li>
                <li>Remove any copyright or other proprietary notations</li>
                <li>
                  Transfer the materials to another person or "mirror" the
                  materials
                </li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                3. Generated Content
              </h2>
              <p className="text-gray-700 mb-4">
                All code, color palettes, design systems, and other content
                generated by our tools are free to use in your personal and
                commercial projects. You retain all rights to your designs and
                implementations.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                4. Account Responsibility
              </h2>
              <p className="text-gray-700 mb-4">
                If you create an account with us, you are responsible for
                maintaining the security of your account and for all activities
                that occur under the account.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                5. Service Modifications
              </h2>
              <p className="text-gray-700 mb-4">
                DesignHub reserves the right to modify or discontinue,
                temporarily or permanently, the Service with or without notice.
                We shall not be liable to you or any third party for any
                modification, suspension, or discontinuance of the Service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                6. Third-Party Services
              </h2>
              <p className="text-gray-700 mb-4">
                Our Service may contain links to third-party websites or
                services that are not owned or controlled by DesignHub. We have
                no control over, and assume no responsibility for, the content,
                privacy policies, or practices of any third-party websites or
                services.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                7. Advertising
              </h2>
              <p className="text-gray-700 mb-4">
                DesignHub uses Google AdSense to display advertisements. By
                using our Service, you agree to the placement of cookies and
                similar technologies as described in our Privacy Policy.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                8. Disclaimer
              </h2>
              <p className="text-gray-700 mb-4">
                The materials on DesignHub are provided on an 'as is' basis.
                DesignHub makes no warranties, expressed or implied, and hereby
                disclaims and negates all other warranties including, without
                limitation, implied warranties or conditions of merchantability,
                fitness for a particular purpose, or non-infringement of
                intellectual property or other violation of rights.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                9. Limitations
              </h2>
              <p className="text-gray-700 mb-4">
                In no event shall DesignHub or its suppliers be liable for any
                damages (including, without limitation, damages for loss of data
                or profit, or due to business interruption) arising out of the
                use or inability to use the materials on DesignHub's website.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                10. Accuracy of Materials
              </h2>
              <p className="text-gray-700 mb-4">
                The materials appearing on DesignHub's website could include
                technical, typographical, or photographic errors. DesignHub does
                not warrant that any of the materials on its website are
                accurate, complete or current.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                11. Links
              </h2>
              <p className="text-gray-700 mb-4">
                DesignHub has not reviewed all of the sites linked to its
                website and is not responsible for the contents of any such
                linked site. The inclusion of any link does not imply
                endorsement by DesignHub of the site.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                12. Modifications
              </h2>
              <p className="text-gray-700 mb-4">
                DesignHub may revise these terms of service for its website at
                any time without notice. By using this website you are agreeing
                to be bound by the then current version of these terms of
                service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                13. Governing Law
              </h2>
              <p className="text-gray-700 mb-4">
                These terms and conditions are governed by and construed in
                accordance with the laws of the United States and you
                irrevocably submit to the exclusive jurisdiction of the courts
                in that location.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                14. Contact Information
              </h2>
              <p className="text-gray-700">
                If you have any questions about these Terms of Service, please
                contact us at{" "}
                <span className="text-purple-600">hsuntariq@gmail.com</span>
              </p>
            </section>
          </div>
        </div>

        {/* Quick Links */}
        <div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-4">
          <Link
            to="/privacy"
            className="bg-white rounded-xl p-6 shadow-lg hover:shadow-xl transition-all duration-300 text-center border border-gray-200 hover:border-purple-300"
          >
            <div className="text-2xl mb-3">🔒</div>
            <h3 className="font-semibold text-gray-900 mb-2">Privacy Policy</h3>
            <p className="text-gray-600 text-sm">Learn about data protection</p>
          </Link>

          <Link
            to="/contact"
            className="bg-white rounded-xl p-6 shadow-lg hover:shadow-xl transition-all duration-300 text-center border border-gray-200 hover:border-purple-300"
          >
            <div className="text-2xl mb-3">📧</div>
            <h3 className="font-semibold text-gray-900 mb-2">Contact Us</h3>
            <p className="text-gray-600 text-sm">Get in touch with our team</p>
          </Link>

          <Link
            to="/support"
            className="bg-white rounded-xl p-6 shadow-lg hover:shadow-xl transition-all duration-300 text-center border border-gray-200 hover:border-purple-300"
          >
            <div className="text-2xl mb-3">🛠️</div>
            <h3 className="font-semibold text-gray-900 mb-2">Support</h3>
            <p className="text-gray-600 text-sm">Get help with our tools</p>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
